# 1. Base Image: Use an official Node.js image.
FROM node:20-alpine AS base

# 2. Set Working Directory
WORKDIR /app

# 3. Install Dependencies
# Use a separate step for dependencies to leverage Docker layer caching.
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# 4. Copy App Code
COPY . .

# 5. Build the Next.js App
RUN npm run build

# 6. Production Image: Create a smaller, final image.
FROM node:20-alpine AS production

WORKDIR /app

# Copy built files from the 'base' stage
COPY --from=base /app/.next ./.next
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/public ./public

# Expose the port the app will run on
EXPOSE 3000

# Command to start the app
CMD ["npm", "start"]
